spring:
  application:
    name: gateway-service

  config:
    import: "configserver:https://config-server-bph7.onrender.com"
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 5
        max-interval: 2000
        initial-interval: 1000

server:
  port: 8080
